
NUM_INFERENCE_STEPS = 30
GUIDANCE_SCALE = 7.5

# CHANGED FROM MM2 TO TRY TO GET THIS TO WORK!!!!! RESET!!!

MARIO_HEIGHT = 20
MARIO_WIDTH = 20

MARIO_TILE_PIXEL_DIM = 16
MARIO_TILE_COUNT = 23

MARIO_TILESET = 'extended_tiles.json'

MM_EXTENDED_TILE_COUNT = 23  # 22 tiles in extended_tiles.json + 1 extra/padding tile
MM_EXTENDED_TILESET = 'extended_tiles.json'

