REM @echo off
REM Usage: prepare-mario-maker-llm.bat <input> [seed]
REM <input> is a path to a .txt ASCII level file or a folder of .txt files
REM [seed]  is optional, defaults to 0
REM
REM Identical to prepare-mario-maker.bat except captions are generated by a
REM local Ollama LLM (llama3.1:8b) instead of the simple tile-presence method.
REM Ollama is started automatically if not already running.
cd ..

set INPUT=%1
if "%INPUT%"=="" (
    echo ERROR: Must provide input path as first argument.
    exit /b 1
)

set SEED=%2
if "%SEED%"=="" set SEED=0

set GAME=MM
set TYPE=regular
set TILESET=extended_tiles.json
set MODEL=qwen2.5:14b

set RAW_OUTPUT=datasets\%GAME%_Levels-%TYPE%.json
set CAPTIONED_OUTPUT=datasets\%GAME%_LevelsAndCaptions-%TYPE%.json

REM ── Ollama setup ────────────────────────────────────────────────────────────
ollama list >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo Ollama not running. Starting ollama serve...
    start /min "" ollama serve
    echo Waiting for Ollama to initialise...
    timeout /t 6 /nobreak >nul
)

echo Pulling %MODEL% ^(no-op if already present^)...
ollama pull %MODEL%
if %ERRORLEVEL% neq 0 (
    echo ERROR: Failed to pull %MODEL%. Is Ollama running?
    exit /b 1
)

REM ── Pipeline ────────────────────────────────────────────────────────────────
python build_dataset_with_ascii.py --input_file %INPUT% --output %RAW_OUTPUT% --tileset %TILESET% --sliding_window --stride 20 --convert_to_extended
python MarioMaker_llm_captions.py --dataset %RAW_OUTPUT% --tileset %TILESET% --output %CAPTIONED_OUTPUT% --model %MODEL%
python split_mario_maker_data.py --json %CAPTIONED_OUTPUT% --seed %SEED%
python tokenizer.py save --json_file datasets\%GAME%_LevelsAndCaptions-%TYPE%-train.json --pkl_file datasets\%GAME%_Tokenizer-%TYPE%.pkl
python create_mario_maker_random_captions.py --json %CAPTIONED_OUTPUT% --output datasets\%GAME%_RandomTest-%TYPE%.json
